# Generated by Django 2.0.5 on 2018-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(null=True, upload_to='notice/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='notice/')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='attached',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='tag_set',
            field=models.ManyToManyField(blank=True, related_name='notices', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(null=True, upload_to='professor/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='attacheds',
            field=models.ManyToManyField(null=True, related_name='notice', to='api.Attached'),
        ),
        migrations.AddField(
            model_name='notice',
            name='images',
            field=models.ManyToManyField(null=True, related_name='notice', to='api.Image'),
        ),
    ]
