# Generated by Django 2.0.5 on 2018-05-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180526_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='photo',
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='professor',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, upload_to='professor/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='lab',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='website',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attached',
            name='attached',
            field=models.FileField(blank=True, upload_to='notice/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='notice/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='notice', to='api.Image'),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='research',
        ),
        migrations.AddField(
            model_name='professor',
            name='biography',
            field=models.ManyToManyField(blank=True, related_name='professor', to='api.Biography'),
        ),
        migrations.AddField(
            model_name='professor',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='professor', to='api.Education'),
        ),
        migrations.AddField(
            model_name='professor',
            name='research',
            field=models.ManyToManyField(blank=True, related_name='professor', to='api.Research'),
        ),
    ]
