# Generated by Django 2.0.5 on 2018-05-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180503_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attached',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
