# Generated by Django 2.0.5 on 2018-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_emeritus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='emeritus',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='research',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='jobs',
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
