# Generated by Django 2.0.5 on 2018-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180603_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeritus',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='edu_emeritus', to='api.StringModel'),
        ),
        migrations.AddField(
            model_name='professor',
            name='biography',
            field=models.ManyToManyField(blank=True, related_name='bio_prof', to='api.StringModel'),
        ),
        migrations.AddField(
            model_name='professor',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='edu_prof', to='api.StringModel'),
        ),
        migrations.AddField(
            model_name='professor',
            name='research',
            field=models.ManyToManyField(blank=True, related_name='research_prof', to='api.StringModel'),
        ),
        migrations.AddField(
            model_name='staff',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='job_staff', to='api.StringModel'),
        ),
    ]
