# Generated by Django 2.0.5 on 2018-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_professor_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='lab',
        ),
        migrations.AddField(
            model_name='lab',
            name='professors',
            field=models.ManyToManyField(null=True, related_name='lab', to='api.Professor'),
        ),
    ]
