# Generated by Django 2.0.5 on 2018-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180603_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lab',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lab',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='lab', to='api.Professor'),
        ),
    ]
