# Generated by Django 2.0.5 on 2018-06-04 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20180603_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnderCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('year', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('link', models.ManyToManyField(blank=True, related_name='under_course', to='api.CourseLink')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
