# Generated by Django 2.0.5 on 2018-06-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_courselink_undercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('start_h', models.IntegerField()),
                ('start_m', models.IntegerField()),
                ('end_h', models.IntegerField()),
                ('end_m', models.IntegerField()),
                ('roomkey', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
    ]
