# Generated by Django 2.0.5 on 2018-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180608_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_h',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_m',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_h',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_m',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
