# Generated by Django 2.0.5 on 2018-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180610_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
