# Generated by Django 2.0.5 on 2018-06-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180610_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
