# Generated by Django 2.0.5 on 2018-06-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180610_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='tag_set',
            new_name='tags',
        ),
    ]
