# Generated by Django 2.0.5 on 2018-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180613_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='attached',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attached',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
