# Generated by Django 2.0.5 on 2018-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180619_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='notices', to='api.Tag'),
        ),
    ]
